hf_repo: autogluon/chronos_datasets
num_rolling_windows: 5
transport_datasets:
  - monash_traffic
transport_dataset_horizons:
  - 24
transport_dataset_seasonalities:
  - 24
energy_datasets:
  - monash_australian_electricity
  - ercot
energy_dataset_horizons:
  - 48
  - 24
energy_dataset_seasonalities:
  - 48
  - 24
