hf_repo: autogluon/chronos_datasets
num_rolling_windows: 5
transport_datasets:
  - monash_traffic
  - taxi_30min
  - uber_tlc_hourly
energy_datasets:
  - electricity_15min
  - solar_1h
  - wind_farms_hourly
