tasks:
  - dataset_path: autogluon/fev_datasets
    dataset_config: entsoe_1H
    horizon: 168
    num_windows: 20
    seasonality: 24
    eval_metric: SQL
    extra_metrics:
      - MASE
      - name: WAPE
        epsilon: 1.0
      - name: WQL
        epsilon: 1.0
    quantile_levels: [0.1, 0.2, 0.3, 0.4, 0.5, 0.6, 0.7, 0.8, 0.9]
    known_dynamic_columns:
      - radiation_diffuse_horizontal
      - temperature
      - radiation_direct_horizontal
    static_columns: []
